// Accounts
export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS';
export const ADD_ACCOUNTS = 'ADD_ACCOUNTS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';

// Transactions
export const RELOAD_TRANSACTIONS_PAGE = 'RELOAD_TRANSACTIONS_PAGE';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';